from __future__ import annotations

from datetime import datetime, timezone

import pytest

import orchestrator.agent.store as store_module
from orchestrator.agent.identity import BootIdentityUnavailable, dmtf_datetime_to_filetime
from orchestrator.agent.store import AgentStore


def test_identity_is_stable_within_boot_and_fenced_per_process(tmp_path) -> None:
    store = AgentStore(tmp_path / "agent.sqlite3")
    store.initialize()

    first = store.initialize_identity("134128800000000000")
    second = store.initialize_identity("134128800000000000")

    assert second.agent_id == first.agent_id
    assert second.boot_id == first.boot_id
    assert second.agent_instance_id != first.agent_instance_id
    assert second.instance_generation == first.instance_generation + 1

    third = store.initialize_identity("134128801000000000")
    assert third.agent_id == first.agent_id
    assert third.boot_id != first.boot_id
    assert third.instance_generation == second.instance_generation + 1


def test_instance_uuid_failure_rolls_back_generation_and_instance_together(
    tmp_path, monkeypatch
) -> None:
    store = AgentStore(tmp_path / "agent.sqlite3")
    store.initialize()
    first = store.initialize_identity("134128800000000000")

    def fail_after_generation_update():
        raise RuntimeError("injected UUID generation failure")

    # With an unchanged boot marker, the only UUID generated by the second
    # initialization is the per-process instance UUID.  Its failure occurs
    # after the in-transaction generation update and must roll both back.
    monkeypatch.setattr(store_module, "uuid4", fail_after_generation_update)
    with pytest.raises(RuntimeError, match="injected UUID generation failure"):
        store.initialize_identity("134128800000000000")

    with store.database.read() as connection:
        row = connection.execute(
            "SELECT instance_generation, current_instance_id FROM agent_identity WHERE singleton=1"
        ).fetchone()
    assert row["instance_generation"] == first.instance_generation
    assert row["current_instance_id"] == str(first.agent_instance_id)


def test_dmtf_boot_time_is_normalized_to_utc_filetime() -> None:
    marker = dmtf_datetime_to_filetime("20260716160000.123456+480")
    expected_utc = datetime(2026, 7, 16, 8, 0, 0, 123456, tzinfo=timezone.utc)
    epoch = datetime(1601, 1, 1, tzinfo=timezone.utc)
    delta = expected_utc - epoch
    expected = (delta.days * 86_400 + delta.seconds) * 10_000_000 + 1_234_560
    assert marker == str(expected)


@pytest.mark.parametrize(
    "value",
    ["", "20260716160000", "2026**********.000000+000", "20260732160000.000000+000"],
)
def test_invalid_wmi_boot_time_is_rejected(value: str) -> None:
    with pytest.raises(BootIdentityUnavailable):
        dmtf_datetime_to_filetime(value)
