from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from orchestrator.acceptance.evidence import (
    AcceptanceEvidence,
    EvidenceInputError,
    load_evidence,
    validate_evidence,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validate an exported Recovery MVP cold-start evidence bundle offline."
    )
    parser.add_argument("evidence", nargs="?", help="UTF-8 JSON evidence bundle")
    parser.add_argument(
        "--report",
        type=Path,
        help="also write the machine-readable validation report as UTF-8 JSON",
    )
    parser.add_argument(
        "--print-schema",
        action="store_true",
        help="print the authoritative JSON Schema generated by the evidence model",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.print_schema:
        print(json.dumps(AcceptanceEvidence.model_json_schema(), ensure_ascii=False, indent=2))
        return 0
    if not args.evidence:
        print("error: evidence is required unless --print-schema is used", file=sys.stderr)
        return 2
    try:
        evidence = load_evidence(args.evidence)
    except EvidenceInputError as exc:
        print(f"INPUT_ERROR: {exc}", file=sys.stderr)
        return 2
    report = validate_evidence(evidence)
    rendered = json.dumps(report.model_dump(mode="json"), ensure_ascii=False, indent=2)
    print(rendered)
    if args.report is not None:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered + "\n", encoding="utf-8")
    return 0 if report.verdict == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
